### ISSUE TITLE
nice match

### ISSUE THREAD

**Issue by gedw99** [joerdav/go-htmx-examples#1]
the templ need to be compiled right ?

I am playing with web components and htmx and just researching best hook up to gol backend

**Comment by gedw99** [comment]
ah i see that yes compile needed

``` 
go run ./cmd/templ generate
```

**Comment by joerdav** [comment]
Yes, there's positives and negatives of this, but the positives are type safety which I'd important to me!

And the only negative is remembering to run generate, in internal projects I've added a PR check that fails if templ generate hasn't been ran.

**Comment by gedw99** [comment]
yep true.. thanks for quick answer.

the LSP integration looks really well thought out.

will pull this and have a play.

**Comment by joerdav** [comment]
Yeah, the author is clued up on LSPs! He's actually doing a talk at the next gophercon UK about how LSPs work and how to implement one in Go.

**Comment by gedw99** [comment]
mhh might be there.

i just grokked the code in 10 minutes. its so clean.

first thing came to mind is to use wazero and wasm and nats. He is using aws lamda...
